Repository awesomemotive/Merchant, pull requests merged in 2024-03, with the labels that each got.

#100 FBT & Free gifts refactor
  admin/classes/class-merchant-admin-options.php
  assets/js/src/admin/admin.js
  assets/js/src/modules/frequently-bought-together/admin/preview.js
  assets/sass/admin/admin.scss
  assets/sass/modules/free-gifts/admin/preview.scss
  assets/sass/modules/frequently-bought-together/admin/preview.scss
  assets/sass/modules/frequently-bought-together/frequently-bought-together.scss
  inc/modules/buy-x-get-y/admin/options.php
  inc/modules/buy-x-get-y/class-buy-x-get-y.php
  inc/modules/free-gifts/admin/options.php
  inc/modules/frequently-bought-together/admin/options.php
  inc/modules/frequently-bought-together/class-frequently-bought-together.php
  merchant.php
  readme.txt
  templates/modules/buy-x-get-y/single-product.php
  templates/modules/free-gifts/widget-contents.php
  templates/modules/frequently-bought-together/single-product.php
  wpgulp.config.js
Labels: bug, enhancement

#108 Adds custom css to hide woo blocks onsale tags
  inc/modules/product-labels/class-product-labels.php
Labels: bug

#109 Adds data-module-id to dashboard modules card
  admin/pages/page-dashboard.php
Labels: enhancement

#113 Datepicker field
  .gitignore
  admin/classes/class-merchant-admin-options.php
  assets/js/src/admin/admin.js
  assets/sass/admin/admin.scss
  assets/vendor/air-datepicker/air-datepicker.css
  assets/vendor/air-datepicker/air-datepicker.js
Labels: enhancement

#120 Tweaks for better B and M overlaping features handling
  admin/pages/page-dashboard.php
  admin/pages/page-module.php
  assets/js/src/admin/admin.js
  inc/classes/class-merchant-modules.php
Labels: enhancement

#118 New module: Storewide sale
  admin/classes/class-merchant-admin-modules.php
  admin/classes/class-merchant-admin-options.php
  assets/js/src/admin/admin.js
  assets/sass/admin/admin.scss
  assets/sass/modules/storewide-sale/admin/preview.scss
  inc/classes/class-merchant-svg-icons.php
  inc/modules/buy-now/admin/options.php
  inc/modules/free-gifts/admin/options.php
  inc/modules/frequently-bought-together/admin/options.php
  inc/modules/storewide-sale/admin/options.php
  inc/modules/storewide-sale/class-storewide-sale.php
  wpgulp.config.js
Labels: enhancement

#121 General Fixes & Improvements
  admin/classes/class-merchant-admin-options.php
  assets/js/src/admin/admin.js
  assets/sass/admin/admin.scss
  inc/class-merchant-loader.php
  inc/compatibility/class-merchant-astra-theme.php
  inc/compatibility/class-merchant-blocksy-theme.php
  inc/compatibility/class-merchant-oceanwp-theme.php
  inc/helpers.php
  inc/modules/free-gifts/admin/options.php
  merchant.php
  readme.txt
Labels: enhancement

#133 Framework Enhancement: Add support for multiple field conditions
  admin/classes/class-merchant-admin-options.php
  assets/js/src/admin/admin.js
Labels: enhancement
