Repository awesomemotive/Merchant, pull requests merged in 2024-04, with the labels that each got.

#135 Stock scarcity: Fix margin on single product products grid
  assets/sass/modules/stock-scarcity/stock-scarcity.scss
Labels: bug

#137 Buy now button don't showing in products that contains pre-order post meta data even though the Pre-Order module is disabled
  inc/modules/buy-now/class-buy-now.php
Labels: enhancement

#138 Fix fields conditional logic
  inc/modules/add-to-cart-text/admin/options.php
  inc/modules/buy-now/admin/options.php
  inc/modules/login-popup/admin/options.php
  inc/modules/product-swatches/admin/options.php
  inc/modules/reasons-to-buy/admin/options.php
  inc/modules/recently-viewed-products/admin/options.php
  inc/modules/wishlist/admin/options.php
Labels: enhancement

#145 Some modules admin inner content description not displaying
  admin/classes/class-merchant-admin-modules.php
  assets/sass/admin/admin.scss
Labels: bug

#154 General fixes related to storewide sale module
  inc/modules/product-labels/class-product-labels.php
Labels: bug-fix

#155 New Module: Added to cart popup
  admin/classes/class-merchant-admin-modules.php
  assets/images/modules/added-to-cart-popup/admin/layout-1.png
  assets/images/modules/added-to-cart-popup/admin/layout-2.png
  assets/images/modules/added-to-cart-popup/admin/layout-3.png
  assets/js/src/admin/admin.js
  assets/js/src/modules/added-to-cart-popup/admin/preview.js
  assets/sass/admin/admin.scss
  assets/sass/modules/added-to-cart-popup/admin/preview.scss
  assets/vendor/slick-slider/slick.css
  assets/vendor/slick-slider/slick.min.js
  inc/classes/class-merchant-svg-icons.php
  inc/modules/added-to-cart-popup/admin/options.php
  inc/modules/added-to-cart-popup/class-added-to-cart-popup.php
  merchant.php
  readme.txt
  templates/modules/added-to-cart-popup/admin/layout-1.php
  templates/modules/added-to-cart-popup/admin/layout-2.php
  templates/modules/added-to-cart-popup/admin/layout-3.php
  templates/modules/added-to-cart-popup/admin/layouts.php
  templates/modules/added-to-cart-popup/common/action-buttons.php
  templates/modules/added-to-cart-popup/common/added-product.php
  templates/modules/added-to-cart-popup/common/buy-x-get-y.php
  templates/modules/added-to-cart-popup/common/frequently-bought-together.php
  templates/modules/added-to-cart-popup/common/popup-header.php
  templates/modules/added-to-cart-popup/common/recently-viewed-products.php
  templates/modules/added-to-cart-popup/common/related-products.php
  templates/modules/added-to-cart-popup/layouts/layout-1.php
  templates/modules/added-to-cart-popup/layouts/layout-2.php
  templates/modules/added-to-cart-popup/layouts/layout-3.php
  templates/modules/added-to-cart-popup/popup-container.php
  wpgulp.config.js
Labels: enhancement
